def PatternCount(text,pattern):
    count = 0
    for i in range(len(text)-len(pattern)+1):
        #print text[i:i+len(pattern)],pattern
        if text[i:i+len(pattern)] == pattern:
            count = count + 1
    return count

#text = input("text, with quotes: ")
#pattern = input("pattern, with quotes: ")

text = "TTGATTCATTGATTCATTTCCAGTCATATTCATTATTCATTCGTAATTCATTGACATTCATTGAATTCATTTGTATTCATTATTCATTGATTCATTGATTCATTATTCATTTCATGTTCGGTATTCATTATTCATTTAATTCATTCCTAGAGTGGCAATTCATTGGATTCATTATTCATTAGGCACTAGGCATTCATTGCATTCATTTGCATTCATTTCCATTCATTATTCATTTCCGTATTCATTGGACATTCATTCGTGATTCATTGCATAAAGTATTCATTAATTGTGGATTCATTAATTCATTCATTCATTGATTCATTGAGTTTTTCATTCATTACCACAAGATTCATTGATTCATTTGGGATTCATTGCCGATTCATTGATTCATTATGTATTCATTGATTCATTATTCATTATTCATTGATAATTCATTATTCATTATTCATTATTCATTGTATTCATTATTCATTCCGATTCATTATTCATTTATTCATTAATTCATTGTATTCATTGATTCATTGGGATTCATTATTCATTCCAGCGATTCATTCTTATTCATTTAAGGATTCATTAACAACCAACATTCATTTACGGTGCATTCATTGGCGGATTCATTATTACCAACATTCATTATTTTGGAACTTTTGCGGGATTCATTGGTAATATTCATTGAACATTCATTGATTCATTCATTCATTAGGATTCATTTATTCATTCAATCAATTCATTACATTCATTAAATTCATTAAAGAAGCATTCATTAATGATTCATTAGATTCATTACTGATTCATTATTCATTCATTCATTAGATTCATTGATTCATTTGATTCATTAGCATTCATTTGATTCATTCTTATTCATTGTAACATCATTCATTCAGATTCATTATTCATTGATTCATTATTCATTCTATTCATTTCTATTCATTTAGCTTAGGACATTCATTACTTTAATTCATTGATTCATTATTCATTTCCGAATTCATTATTCATTATTCATTATAATTCATTATTCATT"
pattern = "ATTCATTAT"

#print "text",text
#print "pattern",pattern

print PatternCount(text,pattern)
